### ISSUE TITLE
Bug with PHP Version 8.3.8 ?

### ISSUE THREAD

**Issue by simogeo** [bugness-chl/sendrecurringinvoicebymail#12]
Hi, thanks for this great extension ! I used to use it with php 7.4 and 19.0.0.

I'm still running the same dolibarr version but now I do use PHP 8.3.8 and since then message is not sending anymore and cron task does not complete.

Here is the log from apache error. Thanks for your help !

`
[Tue Jun 25 12:50:51.872399 2024] [php:warn] [pid 1345748] [client 78.194.240.218:52486] PHP Warning:  Undefined array key 0 in /mydoli/htdocs/core/class/CMailFile.class.php on line 317, referer: https://mydoli.org/cron/card.php?action=execute&token=xxx&id=2&securitykey=yyyy
[Tue Jun 25 12:51:00.078416 2024] [php:error] [pid 1345748] [client 78.194.240.218:52486] PHP Fatal error:  Uncaught TypeError: preg_split(): Argument #2 ($subject) must be of type string, array given in /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php:312\nStack trace:\n#0 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php(312): preg_split()\n#1 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php(259): Swift_Mime_Headers_AbstractHeader->getEncodableWordTokens()\n#2 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/UnstructuredHeader.php(103): Swift_Mime_Headers_AbstractHeader->encodeWords()\n#3 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(309): Swift_Mime_Headers_UnstructuredHeader->getFieldBody()\n#4 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(529): Swift_Mime_SimpleHeaderSet->toString()\n#5 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(601): Swift_Mime_SimpleMimeEntity->toByteStream()\n#6 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Message.php(162): Swift_Mime_SimpleMessage->toByteStream()\n#7 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(400): Swift_Message->toByteStream()\n#8 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(502): Swift_Transport_AbstractSmtpTransport->streamMessage()\n#9 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(517): Swift_Transport_AbstractSmtpTransport->doMailTransaction()\n#10 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()\n#11 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send()\n#12 /mydoli/htdocs/core/class/CMailFile.class.php(1192): Swift_Mailer->send()\n#13 /mydoli/htdocs/custom/sendrecurringinvoicebymail/class/actions_sendrecurringinvoicebymail.class.php(174): CMailFile->sendfile()\n#14 /mydoli/htdocs/core/class/hookmanager.class.php(254): Actionssendrecurringinvoicebymail->afterCreationOfRecurringInvoice()\n#15 /mydoli/htdocs/compta/facture/class/facture-rec.class.php(1421): HookManager->executeHooks()\n#16 /mydoli/htdocs/cron/class/cronjob.class.php(1296): FactureRec->createRecurringInvoices()\n#17 /mydoli/htdocs/cron/card.php(105): Cronjob->run_jobs()\n#18 {main}\n  thrown in /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php on line 312, referer: https://mydoli.org/cron/card.php?action=execute&token=xxx&id=2&securitykey=yyy
[Tue Jun 25 12:54:28.698596 2024] [php:warn] [pid 1345747] [client 78.194.240.218:34382] PHP Warning:  Undefined variable $tmpfieldlist in /mydoli/htdocs/admin/mails_templates.php on line 1099, referer: https://mydoli.org/admin/mails_templates.php
[Tue Jun 25 12:54:28.698631 2024] [php:warn] [pid 1345747] [client 78.194.240.218:34382] PHP Warning:  Undefined variable $tmpfieldlist in /mydoli/htdocs/admin/mails_templates.php on line 1099, referer: https://mydoli.org/admin/mails_templates.php
[Tue Jun 25 12:55:43.131947 2024] [php:warn] [pid 1345926] [client 78.194.240.218:44694] PHP Warning:  Undefined array key 0 in /mydoli/htdocs/core/class/CMailFile.class.php on line 317, referer: https://mydoli.org/cron/card.php?action=execute&token=xxx&id=2&securitykey=yyy
[Tue Jun 25 12:55:50.841893 2024] [php:error] [pid 1345926] [client 78.194.240.218:44694] PHP Fatal error:  Uncaught TypeError: preg_split(): Argument #2 ($subject) must be of type string, array given in /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php:312\nStack trace:\n#0 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php(312): preg_split()\n#1 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php(259): Swift_Mime_Headers_AbstractHeader->getEncodableWordTokens()\n#2 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/UnstructuredHeader.php(103): Swift_Mime_Headers_AbstractHeader->encodeWords()\n#3 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(309): Swift_Mime_Headers_UnstructuredHeader->getFieldBody()\n#4 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(529): Swift_Mime_SimpleHeaderSet->toString()\n#5 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(601): Swift_Mime_SimpleMimeEntity->toByteStream()\n#6 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Message.php(162): Swift_Mime_SimpleMessage->toByteStream()\n#7 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(400): Swift_Message->toByteStream()\n#8 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(502): Swift_Transport_AbstractSmtpTransport->streamMessage()\n#9 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(517): Swift_Transport_AbstractSmtpTransport->doMailTransaction()\n#10 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()\n#11 /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send()\n#12 /mydoli/htdocs/core/class/CMailFile.class.php(1192): Swift_Mailer->send()\n#13 /mydoli/htdocs/custom/sendrecurringinvoicebymail/class/actions_sendrecurringinvoicebymail.class.php(174): CMailFile->sendfile()\n#14 /mydoli/htdocs/core/class/hookmanager.class.php(254): Actionssendrecurringinvoicebymail->afterCreationOfRecurringInvoice()\n#15 /mydoli/htdocs/compta/facture/class/facture-rec.class.php(1421): HookManager->executeHooks()\n#16 /mydoli/htdocs/cron/class/cronjob.class.php(1296): FactureRec->createRecurringInvoices()\n#17 /mydoli/htdocs/cron/card.php(105): Cronjob->run_jobs()\n#18 {main}\n  thrown in /mydoli/htdocs/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php on line 312, referer: https://mydoli.org/cron/card.php?action=execute&token=xxx&id=2&securitykey=yyy

`

**Comment by simogeo** [comment]
By the way, I'm able to send email. My SMTP config is all well !

**Comment by bugness-chl** [comment]
Hello,

this looks similar to #9, could you patch the file `class/actions_sendrecurringinvoicebymail.class.php` like this :
```diff
--- a/class/actions_sendrecurringinvoicebymail.class.php
+++ b/class/actions_sendrecurringinvoicebymail.class.php
@@ -171,6 +171,9 @@ class Actionssendrecurringinvoicebymail
             'standard', // sendcontext
             $mail_data['replyTo']);
 
+error_log(print_r($mailfile, true));
+error_log(print_r($filePath[0], true));
+
         if ($mailfile->sendfile()) {
             dol_syslog("Success sending email for " . $facturerec->ref . " (id:" . $facturerec->id . ").");
 
```
and send your logs (after redacting confidential info), or compare it to mine ?
```
***** cron_run_jobs.php (18.0.4) pid=722 - userlogin=admin - 2024-03-15T00:37:45Z - vm-dolibarr-dev2.local *****
cron_run_jobs.php cronjobid: 4 priority=50 entity=0 label=PurgeDeleteTemporaryFilesShort - not qualified
cron_run_jobs.php cronjobid: 1 priority=51 entity=1 label=RecurringInvoicesJob - qualifiedPHP Warning:  Undefined array key 0 in htdocs/core/class/CMailFile.class.php on line 306
object(CMailFile)#152 (43) {
  ["sendcontext"]=>
  string(8) "standard"
  ["sendmode"]=>
  string(11) "swiftmailer"
  ["sendsetup"]=>
  NULL
  ["subject"]=>
  string(48) "[My Big and New Company] New invoice FA2312-0008"
  ["addr_from"]=>
  string(16) "robot@domain.com"
  ["reply_to"]=>
  string(16) "robot@domain.com"
  ["errors_to"]=>
  string(0) ""
  ["addr_to"]=>
  string(27) "postmaster+dest@localhost"
  ["addr_cc"]=>
  string(0) ""
  ["addr_bcc"]=>
  string(0) ""
  ["trackid"]=>
  string(0) ""
  ["mixed_boundary"]=>
  string(33) "multipart_x.1710463065.x_boundary"
  ["related_boundary"]=>
  string(36) "mul_7b7eeeb35baa34379e1452fe237c2af4"
  ["alternative_boundary"]=>
  string(36) "mul_dc430f39c8ee8d18cb5a522a60ad4998"
  ["deliveryreceipt"]=>
  int(0)
  ["atleastonefile"]=>
  int(1)
  ["msg"]=>
  string(366) "Hello,

Please find attached your new invoice. Yeah ! Top !

In case of payment via bank transfer (our bank infos added at the bottom of the invoice), remember to add some references :
- invoice number FA2312-0008 for a one-time transfer,
- or the contract/subscription reference __CONTRACT_REF__ for periodic transfers.

Sincerely,

My Big and New Company"
  ["eol"]=>
  string(1) "
"
  ["eol2"]=>
  string(1) "
"
  ["error"]=>
  string(0) ""
  ["errors"]=>
  array(0) {
  }
  ["smtps"]=>
  NULL
  ["phpmailer"]=>
  NULL
  ["transport"]=>
  NULL
  ["mailer"]=>
  NULL
  ["logger"]=>
  NULL
  ["css"]=>
  NULL
  ["styleCSS"]=>
  NULL
  ["bodyCSS"]=>
  NULL
  ["msgid"]=>
  string(73) "1710463065.swiftmailer-dolibarr-@f1a30bcc14c92f23b333adb06b1a467727cd7ceb"
  ["headers"]=>
  NULL
  ["message"]=>
  object(Swift_Message)#162 (23) {
    [... too long ...]
  }
  ["filename_list"]=>
  array(1) {
    [0]=>
    string(54) "/srv/Docs-dolibarr/facture/FA2312-0008/FA2312-0008.pdf"
  }
  ["mimetype_list"]=>
  array(1) {
    [0]=>
    string(15) "application/pdf"
  }
  ["mimefilename_list"]=>
  array(1) {
    [0]=>
    string(15) "FA2312-0008.pdf"
  }
  ["cid_list"]=>
  array(0) {
  }
  ["html"]=>
  NULL
  ["msgishtml"]=>
  string(1) "0"
  ["image_boundary"]=>
  NULL
  ["atleastoneimage"]=>
  int(0)
  ["html_images"]=>
  array(0) {
  }
  ["images_encoded"]=>
  array(0) {
  }
  ["image_types"]=>
  array(8) {
    ["gif"]=>
    string(9) "image/gif"
    ["jpg"]=>
    string(10) "image/jpeg"
    ["jpeg"]=>
    string(10) "image/jpeg"
    ["jpe"]=>
    string(10) "image/jpeg"
    ["bmp"]=>
    string(9) "image/bmp"
    ["png"]=>
    string(9) "image/png"
    ["tif"]=>
    string(10) "image/tiff"
    ["tiff"]=>
    string(10) "image/tiff"
  }
}
array(26) {
  [0]=>
  int(70)
  [1]=>
  int(59665)
  [2]=>
  int(33200)
  [3]=>
  int(1)
  [4]=>
  int(33)
  [5]=>
  int(33)
  [6]=>
  int(0)
  [7]=>
  int(26350)
  [8]=>
  int(1710463065)
  [9]=>
  int(1710463065)
  [10]=>
  int(1710463065)
  [11]=>
  int(4096)
  [12]=>
  int(56)
  ["dev"]=>
  int(70)
  ["ino"]=>
  int(59665)
  ["mode"]=>
  int(33200)
  ["nlink"]=>
  int(1)
  ["uid"]=>
  int(33)
  ["gid"]=>
  int(33)
  ["rdev"]=>
  int(0)
  ["size"]=>
  int(26350)
  ["atime"]=>
  int(1710463065)
  ["mtime"]=>
  int(1710463065)
  ["ctime"]=>
  int(1710463065)
  ["blksize"]=>
  int(4096)
  ["blocks"]=>
  int(56)
}
 - run_jobs OK result = 1 - reprogrammed
cron_run_jobs.php cronjobid: 3 priority=51 entity=1 label=RecurringSupplierInvoicesJob - qualifiedPHP Warning:  Undefined property: FactureFournisseurRec::$fk_soc in htdocs/fourn/class/fournisseur.facture-rec.class.php on line 489
 - run_jobs OK result = 1 - reprogrammed
```

Also, beware : PHP 8.3 is not yet supported by Dolibarr : https://wiki.dolibarr.org/index.php?title=Releases#List_of_Versions_and_compatibility

**Comment by simogeo** [comment]
Many thanks for your quick reply !

I have applied the patch to get more debug information. Bu, I've edited my invoices manually. So, I'll have to wait for one month before the next cron call ... But I'll let you know.

And by the way, I've downgraded my PHP version to 8.1. Thanks for pointing this point out.

**Comment by bugness-chl** [comment]
No activity for a while : closing the issue, assuming it was fixed with the downgrading of the PHP version.
Don't hesitate to reopen if needed.
