### ISSUE TITLE
Fails with 18.0.4 

### ISSUE THREAD

**Issue by vsatmydynipnet** [bugness-chl/sendrecurringinvoicebymail#9]
Hi,

i run your code on my setup and it worked pretty cool since month.  Now I updated from 17.0.3 to 18.0.4 and without any other change recurring job fails with:

```
cron_run_jobs.php cronjobid: 1 priority=50 entity=1 label=RecurringInvoicesJob - qualifiedPHP Warning:  Undefined property: TCPDI::$page_largeur in /var/www/VHOST-hpanel-SSL/demo01/core/lib/pdf.lib.php on line 1255
PHP Warning:  Undefined property: TCPDI::$margin_left in /var/www/VHOST-hpanel-SSL/demo01/core/lib/pdf.lib.php on line 1255
PHP Warning:  Undefined property: TCPDI::$margin_right in /var/www/VHOST-hpanel-SSL/demo01/core/lib/pdf.lib.php on line 1255
PHP Warning:  Undefined array key 0 in /var/www/VHOST-hpanel-SSL/demo01/core/class/CMailFile.class.php on line 306
PHP Fatal error:  Uncaught TypeError: preg_split(): Argument #2 ($subject) must be of type string, array given in /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php:312
Stack trace:
#0 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php(312): preg_split()
#1 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php(259): Swift_Mime_Headers_AbstractHeader->getEncodableWordTokens()
#2 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mime/Headers/UnstructuredHeader.php(103): Swift_Mime_Headers_AbstractHeader->encodeWords()
#3 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(309): Swift_Mime_Headers_UnstructuredHeader->getFieldBody()
#4 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(529): Swift_Mime_SimpleHeaderSet->toString()
#5 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(601): Swift_Mime_SimpleMimeEntity->toByteStream()
#6 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Message.php(162): Swift_Mime_SimpleMessage->toByteStream()
#7 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(400): Swift_Message->toByteStream()
#8 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(502): Swift_Transport_AbstractSmtpTransport->streamMessage()
#9 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(517): Swift_Transport_AbstractSmtpTransport->doMailTransaction()
#10 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()
#11 /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send()
#12 /var/www/VHOST-hpanel-SSL/demo01/core/class/CMailFile.class.php(1165): Swift_Mailer->send()
#13 /var/www/VHOST-hpanel-SSL/demo01/custom/sendrecurringinvoicebymail/class/actions_sendrecurringinvoicebymail.class.php(166): CMailFile->sendfile()
#14 /var/www/VHOST-hpanel-SSL/demo01/core/class/hookmanager.class.php(254): Actionssendrecurringinvoicebymail->afterCreationOfRecurringInvoice()
#15 /var/www/VHOST-hpanel-SSL/demo01/compta/facture/class/facture-rec.class.php(1403): HookManager->executeHooks()
#16 /var/www/VHOST-hpanel-SSL/demo01/cron/class/cronjob.class.php(1290): FactureRec->createRecurringInvoices()
#17 /var/www/VHOST-hpanel-SSL-scripts-demo01/extra/scripts/cron/cron_run_jobs.php(257): Cronjob->run_jobs()
#18 {main}
  thrown in /var/www/VHOST-hpanel-SSL/demo01/includes/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php on line 312
```
I already tried to find which of their changes causes the problem, but have not found anything helpful.  I use Swiftmailer because smtp/smtps lib does not work with my sendmail setup. All other mails out of 18.0.4 works. So creating the invoice manually, even with the same mail template and subject, works fine.

Thank you for any hints.

**Comment by bugness-chl** [comment]
Sorry, I couldn't reproduce, at least with a basic Swift configuration.
Unless there is a problem with the PDF generation (hinted by your PHP warnings), I also presume this is Dolibarr issue.

Eventually, could you patch the file `class/actions_sendrecurringinvoicebymail.class.php` like this :
```diff
--- a/class/actions_sendrecurringinvoicebymail.class.php
+++ b/class/actions_sendrecurringinvoicebymail.class.php
@@ -171,6 +171,9 @@ class Actionssendrecurringinvoicebymail
             'standard', // sendcontext
             $mail_data['replyTo']);
 
+var_dump($mailfile);
+var_dump(stat($filePath[0]));
+
         if ($mailfile->sendfile()) {
             dol_syslog("Success sending email for " . $facturerec->ref . " (id:" . $facturerec->id . ").");
 
```
and send your output (after redacting confidential info), or compare it to mine ?
```
***** cron_run_jobs.php (18.0.4) pid=722 - userlogin=admin - 2024-03-15T00:37:45Z - vm-dolibarr-dev2.local *****
cron_run_jobs.php cronjobid: 4 priority=50 entity=0 label=PurgeDeleteTemporaryFilesShort - not qualified
cron_run_jobs.php cronjobid: 1 priority=51 entity=1 label=RecurringInvoicesJob - qualifiedPHP Warning:  Undefined array key 0 in htdocs/core/class/CMailFile.class.php on line 306
object(CMailFile)#152 (43) {
  ["sendcontext"]=>
  string(8) "standard"
  ["sendmode"]=>
  string(11) "swiftmailer"
  ["sendsetup"]=>
  NULL
  ["subject"]=>
  string(48) "[My Big and New Company] New invoice FA2312-0008"
  ["addr_from"]=>
  string(16) "robot@domain.com"
  ["reply_to"]=>
  string(16) "robot@domain.com"
  ["errors_to"]=>
  string(0) ""
  ["addr_to"]=>
  string(27) "postmaster+dest@localhost"
  ["addr_cc"]=>
  string(0) ""
  ["addr_bcc"]=>
  string(0) ""
  ["trackid"]=>
  string(0) ""
  ["mixed_boundary"]=>
  string(33) "multipart_x.1710463065.x_boundary"
  ["related_boundary"]=>
  string(36) "mul_7b7eeeb35baa34379e1452fe237c2af4"
  ["alternative_boundary"]=>
  string(36) "mul_dc430f39c8ee8d18cb5a522a60ad4998"
  ["deliveryreceipt"]=>
  int(0)
  ["atleastonefile"]=>
  int(1)
  ["msg"]=>
  string(366) "Hello,

Please find attached your new invoice. Yeah ! Top !

In case of payment via bank transfer (our bank infos added at the bottom of the invoice), remember to add some references :
- invoice number FA2312-0008 for a one-time transfer,
- or the contract/subscription reference __CONTRACT_REF__ for periodic transfers.

Sincerely,

My Big and New Company"
  ["eol"]=>
  string(1) "
"
  ["eol2"]=>
  string(1) "
"
  ["error"]=>
  string(0) ""
  ["errors"]=>
  array(0) {
  }
  ["smtps"]=>
  NULL
  ["phpmailer"]=>
  NULL
  ["transport"]=>
  NULL
  ["mailer"]=>
  NULL
  ["logger"]=>
  NULL
  ["css"]=>
  NULL
  ["styleCSS"]=>
  NULL
  ["bodyCSS"]=>
  NULL
  ["msgid"]=>
  string(73) "1710463065.swiftmailer-dolibarr-@f1a30bcc14c92f23b333adb06b1a467727cd7ceb"
  ["headers"]=>
  NULL
  ["message"]=>
  object(Swift_Message)#162 (23) {
    [... too long ...]
  }
  ["filename_list"]=>
  array(1) {
    [0]=>
    string(54) "/srv/Docs-dolibarr/facture/FA2312-0008/FA2312-0008.pdf"
  }
  ["mimetype_list"]=>
  array(1) {
    [0]=>
    string(15) "application/pdf"
  }
  ["mimefilename_list"]=>
  array(1) {
    [0]=>
    string(15) "FA2312-0008.pdf"
  }
  ["cid_list"]=>
  array(0) {
  }
  ["html"]=>
  NULL
  ["msgishtml"]=>
  string(1) "0"
  ["image_boundary"]=>
  NULL
  ["atleastoneimage"]=>
  int(0)
  ["html_images"]=>
  array(0) {
  }
  ["images_encoded"]=>
  array(0) {
  }
  ["image_types"]=>
  array(8) {
    ["gif"]=>
    string(9) "image/gif"
    ["jpg"]=>
    string(10) "image/jpeg"
    ["jpeg"]=>
    string(10) "image/jpeg"
    ["jpe"]=>
    string(10) "image/jpeg"
    ["bmp"]=>
    string(9) "image/bmp"
    ["png"]=>
    string(9) "image/png"
    ["tif"]=>
    string(10) "image/tiff"
    ["tiff"]=>
    string(10) "image/tiff"
  }
}
array(26) {
  [0]=>
  int(70)
  [1]=>
  int(59665)
  [2]=>
  int(33200)
  [3]=>
  int(1)
  [4]=>
  int(33)
  [5]=>
  int(33)
  [6]=>
  int(0)
  [7]=>
  int(26350)
  [8]=>
  int(1710463065)
  [9]=>
  int(1710463065)
  [10]=>
  int(1710463065)
  [11]=>
  int(4096)
  [12]=>
  int(56)
  ["dev"]=>
  int(70)
  ["ino"]=>
  int(59665)
  ["mode"]=>
  int(33200)
  ["nlink"]=>
  int(1)
  ["uid"]=>
  int(33)
  ["gid"]=>
  int(33)
  ["rdev"]=>
  int(0)
  ["size"]=>
  int(26350)
  ["atime"]=>
  int(1710463065)
  ["mtime"]=>
  int(1710463065)
  ["ctime"]=>
  int(1710463065)
  ["blksize"]=>
  int(4096)
  ["blocks"]=>
  int(56)
}
 - run_jobs OK result = 1 - reprogrammed
cron_run_jobs.php cronjobid: 3 priority=51 entity=1 label=RecurringSupplierInvoicesJob - qualifiedPHP Warning:  Undefined property: FactureFournisseurRec::$fk_soc in htdocs/fourn/class/fournisseur.facture-rec.class.php on line 489
 - run_jobs OK result = 1 - reprogrammed
```

**Comment by bugness-chl** [comment]
No activity for a while and couldn't reproduce : closing the issue.
Don't hesitate to reopen it if the problem still lingers.
